source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'
install! 'cocoapods', disable_input_output_paths: true
abstract_target 'DbyPaas' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'MBProgressHUD'  
  pod 'DbyPaas_iOS', '~> 1.0.0-8'
  pod 'AgoraRtcEngine_iOS'
  #pod 'DbyPaas_iOS', path: '~/Projects/compare_agora/dby-paas-ios-sdk/DbyPaas_iOS.podspec'
  
  target 'DbyPaas_Demo' do
    pod 'QRCodeReader.swift', '~> 10.1.0'
    pod 'SnapKit'
  end 

  target 'DbyPaas_Demo_OC' do 
    pod 'Masonry'
  end
end
